baas/trees/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the AddTreeFile
    url(
        regex=r'^$',
        view=views.StudyListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^add/$',
        view=views.AddTreeFileView.as_view(),
        name='add'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/(?P<version>[\d.-]+)/~edit/$',
        view=views.EditTree.as_view(),
        name='edit'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/(?P<version>[\d.-]+)/$',
        view=views.JustJSONView.as_view(),
        name='json'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/$',
        view=views.StudyDetailListView.as_view(),
        name='detail_list'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/~version/$',
        view=views.AddTreeVersionView.as_view(),
        name='version'
    ),
]

baas/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^add-to-group/(?P<study_slug>[\w.@+-]+)/$',
        view=views.AddToGroupView.as_view(),
        name='add_to_group'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^update-group/(?P<study_slug>[\w.@+-]+)/(?P<username>[\w.@+-]+)/$',
        view=views.UpdateGroupView.as_view(),
        name='update_group'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^demo/$', TemplateView.as_view(template_name='pages/demo.html'), name='demo'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('baas.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^trees/', include('baas.trees.urls', namespace='trees')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

baas/trees/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from jsonfield import JSONField


class Study(models.Model):
    name = models.CharField(_('Name of Study'), max_length=50, blank=False)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)

    def special_tree_add(self, *args, **kwargs):
        self.trees.add(
            tree=Tree(project=self, *args, **kwargs)
        )

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)
        super(Study, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trees:detail_list', kwargs={'name': str(self)})


@python_2_unicode_compatible
class Tree(models.Model):
    version = models.IntegerField(_('Version'), blank=False)
    created_by = models.CharField(_('Created by'), blank=True, max_length=255)
    save_date = models.DateTimeField(auto_now_add=True)
    json = JSONField('Enter a valid Treefile JSON:')
    study = models.ForeignKey("trees.Study", related_name="trees")

    def __str__(self):
        return '{} version {}'.format(self.study.name, self.version)

    def get_absolute_url(self):
        return reverse('trees:detail', kwargs={'study_slug': self.study.slug,
                                               'version': self.version})

baas/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser, Group
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _



@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

baas/trees/forms.py
from django import forms

from .models import Tree, Study


class CreateStudyForm(forms.ModelForm):
    """
    A form that creates a associated project for a Treefile.
    """
    class Meta:
        model = Study
        fields = ["name", ]


class AddTreeForm(forms.ModelForm):
    """
    A form that creates a new version of a TreeFile
    """
    class Meta:
        model = Tree
        fields = ["json", ]

baas/trees/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import json

from django.core.urlresolvers import reverse
from django.views.generic import ListView, UpdateView, TemplateView, View

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import Group, User

from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden

from django.template import RequestContext

from django.utils.decorators import method_decorator

from django.template.defaultfilters import slugify

from .models import Tree, Study
from .forms import CreateStudyForm, AddTreeForm

from guardian.shortcuts import assign_perm, get_objects_for_user
from guardian.decorators import permission_required_or_403


class AddTreeFileView(PermissionRequiredMixin, UpdateView):
    # Require permission to add trees, if not it raises an exception
    permission_required = 'trees.add_tree'
    raise_exception = True

    template_name = 'trees/tree_form.html'

    def get(self, request):
        return render_to_response(self.template_name,
                                  {'form_tree': AddTreeForm(),
                                   'form_study': CreateStudyForm()},
                                  context_instance=RequestContext(request))

    def post(self, request):
        form_study = CreateStudyForm(request.POST)
        form_tree = AddTreeForm(request.POST)

        if not form_study.is_valid():
            m = 'You should pick a new name for the study.'
            messages.add_message(request, messages.ERROR, m)
            return HttpResponseRedirect(reverse('trees:add'))

        new_slug = slugify(form_study.cleaned_data['name'])

        if Study.objects.filter(slug=new_slug):
            m = 'This name is already taken, pick a different one.'
            messages.add_message(request, messages.ERROR, m)
            return HttpResponseRedirect(reverse('trees:add'))

        if not form_tree.is_valid():
            m = 'Something is wrong with the Tree, it is not a valid JSON format!'
            messages.add_message(request, messages.ERROR, m)
            return HttpResponseRedirect(reverse('trees:add'))

        study = form_study.save()

        tree = form_tree.save(commit=False)
        tree.created_by = request.user.username
        tree.study = study
        tree.version = 1
        tree.save()

        self.create_group(study.slug, request.user, study)

        return HttpResponseRedirect(reverse('trees:detail_list',
                                            kwargs={'study_slug': study.slug})
                                    )

    def create_group(self, name, user, study):
        # Create a new group with name of the study and add the user that adds it to db
        new_group = Group(name=name)
        new_group.save()
        user.groups.add(new_group)

        # Add permission to hange this tree to that specific group
        assign_perm('trees.change_study', new_group, study)


class StudyListView(LoginRequiredMixin, ListView):
    model = Study

    def get_queryset(self):
        """Return the trees a user should be able to access."""
        allowed_objects = get_objects_for_user(user=self.request.user, perms='trees.change_study')
        return allowed_objects.order_by('name')


class JustJSONView(LoginRequiredMixin, View):
    model = Tree

    def get(self, *args, **kwargs):
        tree = self.get_object()
        return HttpResponse(json.dumps(tree.json), content_type='application/json')

    def get_object(self):
        study_slug = self.kwargs['study_slug']
        version = self.kwargs['version']
        return self.model.objects.get(study__slug=study_slug, version=version)

    @permission_required_or_403('trees.change_study', (Study, 'slug', 'study_slug'))
    def dispatch(self, *args, **kwargs):
        return super(JustJSONView, self).dispatch(*args, **kwargs)

    @property
    def user(self):
        return self.request.user


class StudyDetailListView(LoginRequiredMixin, ListView):
    model = Study
    template_name_suffix = '_detail_list'

    @permission_required_or_403('trees.change_study', (Study, 'slug', 'study_slug'))
    def dispatch(self, *args, **kwargs):
        return super(StudyDetailListView, self).dispatch(*args, **kwargs)

    def versions(self):
        study_slug = self.kwargs['study_slug']
        return Tree.objects.filter(study__slug=study_slug).order_by('-save_date')

    def editors(self):
        """Return the last five published questions."""
        study_slug = self.kwargs['study_slug']
        g = Group.objects.get(name=study_slug)
        return g.user_set.all()

    @property
    def study(self):
        return self.model.objects.get(slug=self.kwargs['study_slug'])

    @property
    def user(self):
        return self.request.user


class EditTree(LoginRequiredMixin, TemplateView):
    model = Tree
    template_name = 'trees/tree_edit.html'

    def json_tree(self):
        return json.dumps(self.tree.json)

    @property
    def version(self):
        return self.kwargs['version']

    # This decorator makes sure the view checks for object
    @method_decorator(permission_required_or_403('trees.change_study',
                                                 (Study, 'slug', 'study_slug'),
                                                 accept_global_perms=True))
    def dispatch(self, *args, **kwargs):
        return super(EditTree, self).dispatch(*args, **kwargs)

    @property
    def tree(self):
        return self.model.objects.get(study__slug=self.kwargs['study_slug'], version=self.version)


class AddTreeVersionView(UpdateView):
    template_name = 'trees/tree_form.html'
    model = Tree

    @permission_required_or_403('trees.change_study', (Study, 'slug', 'study_slug'))
    def dispatch(self, *args, **kwargs):
        return super(AddTreeVersionView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = AddTreeForm(request.POST)

        if form.is_valid():
            tree = form.save(commit=False)

            tree.created_by = request.user.username
            tree.version = self.highest_version() + 1
            tree.study = self.study

            tree.save()

            return HttpResponseRedirect(reverse('trees:detail_list',
                                                kwargs={'study_slug': self.study.slug})
                                        )
        else:
            # TODO add alert that form is invalid
            return HttpResponseForbidden()

    def highest_version(self):
        trees = self.model.objects.filter(study__slug=self.kwargs['study_slug'])
        return max([t.version for t in trees])

    @property
    def version(self):
        return self.kwargs['version']

    @property
    def study(self):
        return Study.objects.get(slug=self.kwargs['study_slug'])

    @property
    def user(self):
        return self.request.user

baas/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from guardian.shortcuts import get_users_with_perms

from .models import User, Group
from ..trees.models import Tree, Study


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class AddToGroupView(PermissionRequiredMixin, ListView):
    # Require permission to add trees, if not it raises an exception
    permission_required = 'trees.add_tree'
    raise_exception = True

    template_name_suffix = '_add_to_group'

    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    @property
    def study(self):
        return Study.objects.get(slug=self.kwargs['study_slug'])

    @property
    def has_access(self):
        return get_users_with_perms(self.study)


class UpdateGroupView(PermissionRequiredMixin, View):
    permission_required = 'trees.add_tree'
    raise_exception = True

    def get(self, request, **kwargs):
        slug = kwargs.get('study_slug')

        # find group for this study and add the user.
        group = Group.objects.get(name=slug)
        username = kwargs.get('username')
        user = User.objects.get(username=username)
        user.groups.add(group)

        return HttpResponseRedirect(reverse('trees:detail_list',
                                    kwargs={'study_slug': slug}))

baas/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}The Arborist{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="tranSMART Arborist">
    <meta name="author" content="Jochem Bijlard">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-4.0.0a5.css' %}" />

    <!-- Your stuff: Third-party css libraries go here -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}



  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">The Arborist</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'demo' %}">{% trans "Demo Study" %}</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'trees:list' %}">{% trans "Trees" %}</a>
                </li>
            </ul>



            <ul class="nav navbar-nav " style="float: right;">
              {% if perms.trees.add_tree %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'trees:add' %}">{% trans "Upload Tree File" %}</a>
                </li>
              {% endif %}
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}

      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="{% static 'js/jquery-1.11.1.js' %}"></script>

      <!-- Tether - a requirement for Bootstrap tooltips -->
      <script src="{% static 'js/tether-1.2.0.js' %}"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="{% static 'js/bootstrap-4.0.0a5.js' %}"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}

  </body>
</html>