baas/trees/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the AddTreeFile
    url(
        regex=r'^$',
        view=views.StudyListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^add/$',
        view=views.AddTreeFileView.as_view(),
        name='add'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/(?P<version>[\d.-]+)/~edit/$',
        view=views.EditTree.as_view(),
        name='edit'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/(?P<version>[\d.-]+)/$',
        view=views.JustJSONView.as_view(),
        name='json'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/$',
        view=views.StudyDetailListView.as_view(),
        name='detail_list'
    ),
    url(
        regex=r'^(?P<study_slug>[\w.@+-]+)/~version/$',
        view=views.AddTreeVersionView.as_view(),
        name='version'
    ),
]

baas/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^add-to-group/(?P<study_slug>[\w.@+-]+)/$',
        view=views.AddToGroupView.as_view(),
        name='add_to_group'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^update-group/(?P<study_slug>[\w.@+-]+)/(?P<username>[\w.@+-]+)/$',
        view=views.UpdateGroupView.as_view(),
        name='update_group'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^demo/$', TemplateView.as_view(template_name='pages/demo.html'), name='demo'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('baas.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^trees/', include('baas.trees.urls', namespace='trees')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

baas/trees/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from jsonfield import JSONField


class Study(models.Model):
    name = models.CharField(_('Name of Study'), max_length=50, blank=False)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)

    def special_tree_add(self, *args, **kwargs):
        self.trees.add(
            tree=Tree(project=self, *args, **kwargs)
        )

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)
        super(Study, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trees:detail_list', kwargs={'name': str(self)})


@python_2_unicode_compatible
class Tree(models.Model):
    version = models.IntegerField(_('Version'), blank=False)
    created_by = models.CharField(_('Created by'), blank=True, max_length=255)
    save_date = models.DateTimeField(auto_now_add=True)
    json = JSONField('Enter a valid Treefile JSON:')
    study = models.ForeignKey("trees.Study", related_name="trees")

    def __str__(self):
        return '{} version {}'.format(self.study.name, self.version)

    def get_absolute_url(self):
        return reverse('trees:detail', kwargs={'study_slug': self.study.slug,
                                               'version': self.version})

baas/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser, Group
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _



@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

baas/trees/forms.py
from django import forms

from .models import Tree, Study


class CreateStudyForm(forms.ModelForm):
    """
    A form that creates a associated project for a Treefile.
    """
    class Meta:
        model = Study
        fields = ["name", ]


class AddTreeForm(forms.ModelForm):
    """
    A form that creates a new version of a TreeFile
    """
    class Meta:
        model = Tree
        fields = ["json", ]

baas/trees/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import json

from django.core.urlresolvers import reverse
from django.views.generic import ListView, UpdateView, TemplateView, View

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import Group, User

from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden

from django.template import RequestContext

from django.utils.decorators import method_decorator

from django.template.defaultfilters import slugify

from .models import Tree, Study
from .forms import CreateStudyForm, AddTreeForm

from guardian.shortcuts import assign_perm, get_objects_for_user
from guardian.decorators import permission_required_or_403


class AddTreeFileView(PermissionRequiredMixin, UpdateView):
    # Require permission to add trees, if not it raises an exception
    permission_required = 'trees.add_tree'
    raise_exception = True

    template_name = 'trees/tree_form.html'

    def get(self, request):
        return render_to_response(self.template_name,
                                  {'form_tree': AddTreeForm(),
                                   'form_study': CreateStudyForm()},
                                  context_instance=RequestContext(request))

    def post(self, request):
        form_study = CreateStudyForm(request.POST)
        form_tree = AddTreeForm(request.POST)

        if not form_study.is_valid():
            m = 'You should pick a new name for the study.'
            messages.add_message(request, messages.ERROR, m)
            return HttpResponseRedirect(reverse('trees:add'))

        new_slug = slugify(form_study.cleaned_data['name'])

        if Study.objects.filter(slug=new_slug):
            m = 'This name is already taken, pick a different one.'
            messages.add_message(request, messages.ERROR, m)
            return HttpResponseRedirect(reverse('trees:add'))

        if not form_tree.is_valid():
            m = 'Something is wrong with the Tree, it is not a valid JSON format!'
            messages.add_message(request, messages.ERROR, m)
            return HttpResponseRedirect(reverse('trees:add'))

        study = form_study.save()

        tree = form_tree.save(commit=False)
        tree.created_by = request.user.username
        tree.study = study
        tree.version = 1
        tree.save()

        self.create_group(study.slug, request.user, study)

        return HttpResponseRedirect(reverse('trees:detail_list',
                                            kwargs={'study_slug': study.slug})
                                    )

    def create_group(self, name, user, study):
        # Create a new group with name of the study and add the user that adds it to db
        new_group = Group(name=name)
        new_group.save()
        user.groups.add(new_group)

        # Add permission to hange this tree to that specific group
        assign_perm('trees.change_study', new_group, study)


class StudyListView(LoginRequiredMixin, ListView):
    model = Study

    def get_queryset(self):
        """Return the trees a user should be able to access."""
        allowed_objects = get_objects_for_user(user=self.request.user, perms='trees.change_study')
        return allowed_objects.order_by('name')


class JustJSONView(LoginRequiredMixin, View):
    model = Tree

    def get(self, *args, **kwargs):
        tree = self.get_object()
        return HttpResponse(json.dumps(tree.json), content_type='application/json')

    def get_object(self):
        study_slug = self.kwargs['study_slug']
        version = self.kwargs['version']
        return self.model.objects.get(study__slug=study_slug, version=version)

    @permission_required_or_403('trees.change_study', (Study, 'slug', 'study_slug'))
    def dispatch(self, *args, **kwargs):
        return super(JustJSONView, self).dispatch(*args, **kwargs)

    @property
    def user(self):
        return self.request.user


class StudyDetailListView(LoginRequiredMixin, ListView):
    model = Study
    template_name_suffix = '_detail_list'

    @permission_required_or_403('trees.change_study', (Study, 'slug', 'study_slug'))
    def dispatch(self, *args, **kwargs):
        return super(StudyDetailListView, self).dispatch(*args, **kwargs)

    def versions(self):
        study_slug = self.kwargs['study_slug']
        return Tree.objects.filter(study__slug=study_slug).order_by('-save_date')

    def editors(self):
        """Return the last five published questions."""
        study_slug = self.kwargs['study_slug']
        g = Group.objects.get(name=study_slug)
        return g.user_set.all()

    @property
    def study(self):
        return self.model.objects.get(slug=self.kwargs['study_slug'])

    @property
    def user(self):
        return self.request.user


class EditTree(LoginRequiredMixin, TemplateView):
    model = Tree
    template_name = 'trees/tree_edit.html'

    def json_tree(self):
        return json.dumps(self.tree.json)

    @property
    def version(self):
        return self.kwargs['version']

    # This decorator makes sure the view checks for object
    @method_decorator(permission_required_or_403('trees.change_study',
                                                 (Study, 'slug', 'study_slug'),
                                                 accept_global_perms=True))
    def dispatch(self, *args, **kwargs):
        return super(EditTree, self).dispatch(*args, **kwargs)

    @property
    def tree(self):
        return self.model.objects.get(study__slug=self.kwargs['study_slug'], version=self.version)


class AddTreeVersionView(UpdateView):
    template_name = 'trees/tree_form.html'
    model = Tree

    @permission_required_or_403('trees.change_study', (Study, 'slug', 'study_slug'))
    def dispatch(self, *args, **kwargs):
        return super(AddTreeVersionView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = AddTreeForm(request.POST)

        if form.is_valid():
            tree = form.save(commit=False)

            tree.created_by = request.user.username
            tree.version = self.highest_version() + 1
            tree.study = self.study

            tree.save()

            return HttpResponseRedirect(reverse('trees:detail_list',
                                                kwargs={'study_slug': self.study.slug})
                                        )
        else:
            # TODO add alert that form is invalid
            return HttpResponseForbidden()

    def highest_version(self):
        trees = self.model.objects.filter(study__slug=self.kwargs['study_slug'])
        return max([t.version for t in trees])

    @property
    def version(self):
        return self.kwargs['version']

    @property
    def study(self):
        return Study.objects.get(slug=self.kwargs['study_slug'])

    @property
    def user(self):
        return self.request.user

baas/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from guardian.shortcuts import get_users_with_perms

from .models import User, Group
from ..trees.models import Tree, Study


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class AddToGroupView(PermissionRequiredMixin, ListView):
    # Require permission to add trees, if not it raises an exception
    permission_required = 'trees.add_tree'
    raise_exception = True

    template_name_suffix = '_add_to_group'

    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    @property
    def study(self):
        return Study.objects.get(slug=self.kwargs['study_slug'])

    @property
    def has_access(self):
        return get_users_with_perms(self.study)


class UpdateGroupView(PermissionRequiredMixin, View):
    permission_required = 'trees.add_tree'
    raise_exception = True

    def get(self, request, **kwargs):
        slug = kwargs.get('study_slug')

        # find group for this study and add the user.
        group = Group.objects.get(name=slug)
        username = kwargs.get('username')
        user = User.objects.get(username=username)
        user.groups.add(group)

        return HttpResponseRedirect(reverse('trees:detail_list',
                                    kwargs={'study_slug': slug}))

baas/templates/trees/study_detail_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Study Tree Files{% endblock %}

{% block content %}
<div class="list-container">
  <div class="header-bar">
     <span class="header-title">{{ view.study.name }}</span>
   </div>
<div class="list-viewport">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Version</th>
          <th>By</th>
          <th>Date</th>
        </tr>
      </thead>

    {% for tree in view.versions %}
      <tr class='clickable-row' onclick="window.document.location='{% url 'trees:edit' tree.study.slug tree.version %}';">
        <td>{{ tree.version }}</td>
        <td>{{ tree.created_by }}</td>
        <td>{{ tree.save_date|date:"j-n-Y  G:i" }}</td>
      </tr>
    {% endfor %}
    </table>


  {% if perms.trees.add_tree %}
  <div style="margin-top: 0.5cm;">
    <h6>Users with permission to edit</h6>
    <table class="table table-hover">
      {% for user in view.editors %}
        <tr class='clickable-row' onclick="window.document.location='{% url 'users:detail' user.username %}';">
          <td>{{ user.username }}</td>
        </tr>
      {% endfor %}
    </table>

    <div>
      <a class="btn btn-sm btn-primary" style="margin: 10px; " href="{% url 'users:add_to_group' view.study.slug %}">Add user to group for access</a>
    </div>
  </div>
    {% endif %}
</div>
</div>
{% endblock %}

baas/templates/trees/study_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Study Tree Files{% endblock %}

{% block content %}

<div class="list-container">
  <div class="header-bar">
    <span class="header-title">List of Projects</span>
  </div>
  <div class="list-viewport">
    <table class="table table-hover">
      {% for study in study_list %}
      <tr class='clickable-row' onclick="window.document.location='{% url 'trees:detail_list' study.slug %}';">
        <td><h5>{{ study.name }}</h5></td>
      </tr>
      {% endfor %}
    </table>
    {% if not study_list %}
    <i>Bummer... It appears you do not have access to any studies, but you can sure try
      out <a href="{% url 'demo' %}">the demo</a>.</i>
    {% endif %}
  </div>
</div>
{% endblock %}

baas/templates/trees/tree_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Tree: {{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object }}</h2>
    </div>
  </div>

<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'trees:edit' object.study.slug object.version%}">Edit Tree</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
    <div class="col-sm-12 ">
        <b> Save date: {{ object.save_date }} </b>
        <br>
        <b> Created by: {{ object.created_by }} </b>

    </div>
</div>
{% endblock content %}

baas/templates/trees/tree_edit.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Boris: {{ view.tree }}{% endblock %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'jstree/themes/default/style.min.css' %}" />
<link rel="stylesheet" href="{% static 'arborist/mainstyle.css' %}" />
{% endblock %}

{% block content %}



<div id="treeanddetails">

  <div id="outer-tree-div">
    <div id="tree-header" class="header-bar">
      <div id="tree-header-title" class="header-title">{{ view.tree.study }} v{{ view.tree.version }}</div>
      <div id="search-container">
        <input class="form-control" type="text" id="search-box" placeholder="Search..."/>
        <img id="search_spinner" src="/static/images/spin.svg">
      </div>
    </div>
    <div id="tree-div"></div>
    <div class="alert alert-info fade show" id="myAlert" role="alert">
      <strong><span id="alert-text"></span></strong>
    </div>
  </div>

  <!-- Here starts shared code between BaaS and Jupyter embedded template. -->
  <div id="details">
    <div id="details-header" class="header-bar">
      <span class="header-title">Details: <span id="nodetype"></span> </span>
    </div>
    <form id="datanodedetails" class="blockform">
      <ul>
        <div class="clinicaldata" hidden>
          File: <span id="filename"></span>(<span id="columnnumber"></span>)
        </div>

        <div class="dfv" hidden>
          Datafile Value: <span id="datafile_value"></span>
        </div>
      </ul>

      <table width="95%">
        <colgroup>
          <col span="1" style="width: 100px;">
          <col span="1">
        </colgroup>
        <tr hidden class="label">
          <td>Label</td>
          <td>
            <input class="form-control form-control-sm" type="text" id="datalabel"/>
          </td>
        </tr>
        <tr hidden class="clinicaldata">
          <td>DLS</td>
          <td>
            <input class="form-control form-control-sm" type="text" id="magic5"/>
          </td>
        </tr>
        <tr hidden class="clinicaldata">
          <td>CVCD</td>
          <td>
            <input class="form-control form-control-sm" type="text" id="magic6"/>
          </td>
        </tr>
        <tr hidden class="clinicaldata">
          <td>
            <input class="form-control form-control-sm" type="checkbox" id="fc"/>
          </td>
          <td>Force Categorical <small>(requires reloading)</small></td>
        </tr>
      </table>

      <div hidden id="tagbox" class="tag-container list-group"></div>

      <input type="submit" class="btn btn-sm btn-secondary" id="apply-changes" value="Apply changes"/>
      <span id="feedback"></span>

      <div hidden id="hdtagbox" class="hdtagdata table-striped">
        <table id="hdtagtable" width="95%">
          <colgroup>
            <col span="1" style="width: 100px;">
            <col span="1" style="width: calc(95% - 100px);">
          </colgroup>
          <tbody id="hdtagtable-body">
          <tr><td colspan="2"><b>Node information</b></td></tr>
          <tr><td>datatype:</td><td id="hd_type"></td></tr>
          <tr><td>tissue type:</td><td id="hd_tissue"></td></tr>
          <tr><td>sample type:</td><td id="hd_sample"></td></tr>
          <tr><td colspan="2"><b>Platform information</b></td></tr>
          <tr><td>title:</td><td id="pl_title"></td></tr>
          <tr><td>marker type:</td><td id="pl_marker_type"></td></tr>
          <tr><td>genome build:</td><td id="pl_genome_build"></td></tr>
          <tr><td>platform ID:</td><td id="pl_id"></td></tr>
          </tbody>
        </table>
      </div>

    </form>
    <!-- End of shared code. -->


    <div id="bottom-btns">

      <form class="form-horizontal" id="edit_form" action="{% url 'trees:version' view.tree.study.slug %}"
            method="post" enctype="multipart/form-data" style="float: right; margin-right: 10px;">
        {% csrf_token %}
        <div class="btn-group" role="group" aria-label="Control buttons">
          <div class="btn-group dropup" role="group">
            <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Templates
            </button>

            <div class="dropdown-menu dropdown-menu-right">
              <h6 class="dropdown-header">Master Templates</h6>
              <button type="button" class="dropdown-item" id="trait-master">TraIT Master Tree</button>
              <button type="button" class="dropdown-item disabled">TraIT Clinical</button>
              <div class="dropdown-divider"></div>
              <h6 class="dropdown-header">Metadata Templates</h6>
              <button type="button" class="dropdown-item " id="fair-study-metadata">FAIR study level</button>
              <div class="dropdown-divider"></div>
              <h6 class="dropdown-header">Other actions</h6>
              <button type="button" class="dropdown-item" id="download-template">Download as template.</button>
              <button type="button" class="dropdown-item" id="template-from-file">Apply from file.</button>
              <input hidden class='file-upload-button' type="file" />
            </div>
          </div>
          <button type="button" class="btn btn-sm btn-secondary" id="download">Download</button>
          <input id='save' class="btn btn-sm btn-secondary" type="submit" value="Save tree!" />
        </div>
      </form>
    </div>

  </div>
</div>

<script type="application/javascript">
  var study_name = "{{ view.tree.study.slug | safe }}";
  var treeData = {{ view.json_tree | safe }};
</script>


{% endblock content %}

{% block javascript %}
{{ block.super }}
<script src="{% static 'jstree/jstree.min.js' %}"></script>
<script src="{% static 'arborist/tree.js' %}"></script>
{% endblock %}

baas/templates/trees/tree_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Add Treefile {% endblock %}

{% block content %}
 <div class="col-md-5">
    <h1>Tree add form</h1>
        <!-- Upload form. Note enctype attribute! -->
        <form class="form-horizontal" action="{% url 'trees:add' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_study|crispy }}
            {{ form_tree|crispy }}
            <p><input type="submit" class="btn btn-secondary" value="Upload"/></p>
        </form>
   </div>
{% endblock %}